#ifndef INC_2DS_ENUMS_H
#define INC_2DS_ENUMS_H

#include <GLFW/glfw3.h>

enum AnglesEn {
	ANGLE_DEGREE,
	ANGLE_RAD
};

enum OriginEnum {
	ORIGIN_CENTER,
	ORIGIN_TOP_LEFT,
	ORIGIN_TOP_RIGHT,
	ORIGIN_BOTTOM_LEFT,
	ORIGIN_BOTTOM_RIGHT
};

enum CursorStateEnum {
	MODE_NORMAL = GLFW_CURSOR_NORMAL,
	MODE_DISABLED = GLFW_CURSOR_DISABLED,
	MODE_HIDDEN = GLFW_CURSOR_HIDDEN
};

enum ColliderType {
	COLLIDER_RECTANGLE,
	COLLIDER_CIRCLE
};

enum TimeEnum {
	TIME_SECS,
	TIME_M_SECS
};

#endif //INC_2DS_ENUMS_H
